"""
Base engine – defines the contract every lamp engine must fulfil.

Each concrete engine receives a validated :class:`~models.parameters.LampParameters`
object and produces a self-contained OpenSCAD script (a plain-text string) that
can be saved as a ``.scad`` file and rendered with OpenSCAD into a 3-D model.
"""

from __future__ import annotations

import textwrap
from abc import ABC, abstractmethod
from typing import List

from models.parameters import LampParameters


class BaseLampEngine(ABC):
    """Abstract base class for all lamp generation engines.

    Subclasses must implement:

    * :meth:`engine_name` – a short human-readable identifier.
    * :meth:`supported_styles` – the list of style names this engine can produce.
    * :meth:`build` – generate and return the OpenSCAD source code.
    """

    # ------------------------------------------------------------------
    # Identity helpers
    # ------------------------------------------------------------------

    @property
    @abstractmethod
    def engine_name(self) -> str:
        """Return the human-readable name of this engine."""

    @property
    @abstractmethod
    def supported_styles(self) -> List[str]:
        """Return the list of style keywords understood by this engine."""

    # ------------------------------------------------------------------
    # Core generation
    # ------------------------------------------------------------------

    @abstractmethod
    def build(self, params: LampParameters) -> str:
        """Generate a complete OpenSCAD script for the lamp described by *params*.

        Parameters
        ----------
        params:
            Fully-populated :class:`~models.parameters.LampParameters` instance.

        Returns
        -------
        str
            A valid OpenSCAD source string ready to be written to a ``.scad`` file.
        """

    # ------------------------------------------------------------------
    # Shared helper utilities available to all engines
    # ------------------------------------------------------------------

    def _file_header(self, params: LampParameters) -> str:
        """Return a comment block that documents the model metadata."""
        return textwrap.dedent(
            f"""
            // ============================================================
            // Lamp Model – generated by {self.engine_name}
            // ============================================================
            // Client   : {params.client_name}
            // Style    : {params.style}
            // Material : {params.material}
            // Color    : {params.color}
            // Width    : {params.width_mm} mm
            // Height   : {params.height_mm} mm
            // Depth    : {params.depth_mm} mm
            // ============================================================
            """
        ).lstrip()

    @staticmethod
    def _openscad_color(color: str) -> str:
        """Wrap a geometry block in an OpenSCAD ``color()`` call."""
        return f'color("{color}")'

    @staticmethod
    def _cylinder(h: float, r1: float, r2: float | None = None, center: bool = False) -> str:
        """Return an OpenSCAD cylinder statement."""
        r2 = r2 if r2 is not None else r1
        c = "true" if center else "false"
        return f"cylinder(h={h}, r1={r1}, r2={r2}, center={c}, $fn=64);"

    @staticmethod
    def _sphere(r: float) -> str:
        return f"sphere(r={r}, $fn=64);"

    @staticmethod
    def _cube(x: float, y: float, z: float, center: bool = False) -> str:
        c = "true" if center else "false"
        return f"cube([{x}, {y}, {z}], center={c});"

    @staticmethod
    def _translate(x: float = 0, y: float = 0, z: float = 0) -> str:
        return f"translate([{x}, {y}, {z}])"

    @staticmethod
    def _rotate(x: float = 0, y: float = 0, z: float = 0) -> str:
        return f"rotate([{x}, {y}, {z}])"

    @staticmethod
    def _union(*children: str) -> str:
        body = "\n    ".join(children)
        return f"union() {{\n    {body}\n}}"

    @staticmethod
    def _difference(*children: str) -> str:
        body = "\n    ".join(children)
        return f"difference() {{\n    {body}\n}}"
